l1=list(map(int,input().split()))
l2=list(map(int,input().split()))
r=[]
i,j=0,0
while(i<len(l1) and j<len(l2)):
    if(l1[i]<l2[j]):
        r.append(l1[i])
        i+=1
    else:
        r.append(l2[j])
        j+=1
if(i==len(l1)):
    while(j<len(l2)):
        r.append(l2[j])
        j+=1
if(j==len(l2)):
    while(i<len(l1)):
          r.append(l1[i])
          i+=1
print(r)
